# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZXFileBrowserDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ZXFileBrowserDemo
  pod 'SnapKit'
  pod 'ZXKitUtil', '~> 4.0'
end
