# Uncomment the next line to define a global platform for your project

platform :ios, '12.0'

target 'DDFileBrowserDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for DDFileBrowserDemo
  pod 'DDUtils/utils', '~> 5.0.0'
  pod 'DDUtils/ui', '~> 5.0.0'
  pod 'HDHUD', '~> 4.1.0'
end